/*
 * FIRMWARE_VERSION.h
 *
 *  Created on: Jun 28, 2014
 *      Author: ehughes
 */

#ifndef LIBLPC43XXFILESYSTEM_SRC_FIRMWARE_VERSION_H_
#define LIBLPC43XXFILESYSTEM_SRC_FIRMWARE_VERSION_H_

#define FIRMWARE_VERSION_STRING	"1.0.Dev"

#endif /* LIBLPC43XXFILESYSTEM_SRC_FIRMWARE_VERSION_H_ */
